data:
  # Proporción de datos a usar (1.0 para usar todos)
  frac: 1.0 
  random_state: 1
  test_size: 0.25
  batch_size: 64

model:
  # Valor por defecto. Optuna lo sobreescribirá.
  name: resnet152 
  # Número de especies a clasificar
  num_classes: 8 
  # Valor por defecto. Optuna lo sobreescribirá.
  freeze_backbone: True

training:
  # Número máximo de épocas para el modo 'run'
  num_epochs: 50 
  # Número máximo de épocas para cada trial de Optuna
  max_tuning_epochs: 15 
  # Valores por defecto para el modo 'run'. Optuna los sobreescribirá.
  lr: 0.01
  momentum: 0.909431
  weight_decay: 0.005
  early_stopping_patience: 5
  device: "cuda"

paths:
  train_features: "data/raw/train_features.csv"
  train_labels: "data/raw/train_labels.csv"
  test_features: "data/raw/test_features.csv"
  submission_format: "data/raw/submission_format.csv"
  # Directorio para el modelo final (después de 'run') o el mejor de 'tune'
  model_output: "outputs/models/best_model_run.pth" 
  logs_output: "outputs/reports/training_log.csv"
  # Base de datos para guardar el estudio de Optuna (para reanudar)
  tuning_db: "sqlite:///outputs/tuning_study.db"